### ISSUE TITLE
The problem of training.

### ISSUE THREAD

**Issue by LIUYUANWEI98** [ChenhongyiYang/PlainMamba#2]
When training the model, I met the error ’AmpEpochBasedRunner should be used with grad_clip‘. How can I fix it?

**Comment by LIUYUANWEI98** [comment]
When I am ready to train PlainMamba-L1 model, I submitted 'sh tool/dist_train.sh plain_mamba_configs/plain_mamba_l1_in1k_300e.py 4' and met the error like the follow:![image](https://github.com/ChenhongyiYang/PlainMamba/assets/61399254/1b862c49-36fa-4bcb-9c72-c9ba8cc4493d)

**Comment by ChenhongyiYang** [comment]
Hi, Can you plz try changing `AmpEpochBasedRunner` to `EpochBasedRunner`?
