### ISSUE TITLE
ModuleNotFoundError: No module named 'mamba_ssm.ops.triton.layernorm'

### ISSUE THREAD

**Issue by LQchen1** [ChenhongyiYang/PlainMamba#6]
![image](https://github.com/ChenhongyiYang/PlainMamba/assets/93528700/688a68db-02b7-46b9-97b2-2836a4a3774e)

**Comment by wzy1845** [comment]
hi I also encountered the same problem. How did you solve it in the end? thank!

**Comment by LQchen1** [comment]
Sorry man, it's been a while and I forgot, maybe you need to go to Mamba2's code for help.
